name: Build for Windows

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up MSVC Dev Cmd
        uses: ilammy/msvc-dev-cmd@7315a94840631165970262a99c72cfb48a65d25d # v1.12.0
        with:
          arch: x64

      - name: Setup `python`
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Build
        run: make build EXECUTABLE_NAME=${{ github.event.repository.name }} DIST_DIR='${{ github.workspace }}\dist'

      - name: Export build
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-windows
          path: ${{ github.workspace }}\dist\*
          if-no-files-found: error
