name: Build for Mac OS

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1.6.0
        with:
          xcode-version: latest

      - name: Setup `python`
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Setup `virtualenv`
        run: pip install virtualenv

      - name: Build
        run: make build DIST_DIR='${{ github.workspace }}/dist'

      - name: Export build
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-macos
          path: ${{ github.workspace }}/dist/*
          if-no-files-found: error
