name: Publish

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build_windows:
    uses: ./.github/workflows/build_windows.yml
  build_macos:
    uses: ./.github/workflows/build_macos.yml
  build_linux:
    uses: ./.github/workflows/build_linux.yml
  release:
    needs: [build_windows, build_macos, build_linux]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            ${{ github.workspace }}/${{ github.event.repository.name }}-windows.zip
            ${{ github.workspace }}/${{ github.event.repository.name }}-macos.zip
            ${{ github.workspace }}/${{ github.event.repository.name }}-linux.zip
